-- Cadet Critical Thinking
-- Run this script once in Supabase -> SQL Editor.
-- The application uses the server-side SUPABASE_SECRET_KEY, so public browser access is not required.

create table if not exists public.cadets (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    class_name text default '',
    created_at timestamptz not null default now(),
    last_login timestamptz
);

create table if not exists public.diagnostics (
    id bigint generated by default as identity primary key,
    cadet_id bigint not null references public.cadets(id) on delete cascade,
    created_at timestamptz not null default now(),
    total integer not null,
    scores_json jsonb not null,
    mistakes_json jsonb not null
);

create table if not exists public.diagnostic_answers (
    id bigint generated by default as identity primary key,
    diagnostic_id bigint not null references public.diagnostics(id) on delete cascade,
    task_id text not null,
    selected text not null,
    correct boolean not null
);

create table if not exists public.training_sessions (
    id bigint generated by default as identity primary key,
    cadet_id bigint not null references public.cadets(id) on delete cascade,
    created_at timestamptz not null default now(),
    score integer not null,
    total integer not null,
    details_json jsonb not null
);

create table if not exists public.task_attempts (
    id bigint generated by default as identity primary key,
    cadet_id bigint not null references public.cadets(id) on delete cascade,
    task_id text not null,
    component integer not null,
    skill text not null,
    correct boolean not null,
    created_at timestamptz not null default now()
);

create table if not exists public.ai_dialogues (
    id bigint generated by default as identity primary key,
    cadet_id bigint not null references public.cadets(id) on delete cascade,
    created_at timestamptz not null default now(),
    user_message text not null,
    ai_message text not null
);

create table if not exists public.ai_tasks (
    id bigint generated by default as identity primary key,
    cadet_id bigint not null references public.cadets(id) on delete cascade,
    created_at timestamptz not null default now(),
    source_task_id text,
    task_json jsonb not null
);

create index if not exists idx_diagnostics_cadet_id on public.diagnostics(cadet_id);
create index if not exists idx_diagnostic_answers_diagnostic_id on public.diagnostic_answers(diagnostic_id);
create index if not exists idx_training_sessions_cadet_id on public.training_sessions(cadet_id);
create index if not exists idx_task_attempts_cadet_id on public.task_attempts(cadet_id);
create index if not exists idx_task_attempts_skill on public.task_attempts(skill);
create index if not exists idx_ai_dialogues_cadet_id on public.ai_dialogues(cadet_id);
create index if not exists idx_ai_tasks_cadet_id on public.ai_tasks(cadet_id);

-- Extra protection for browser/public access. The server-side secret key used by
-- the Streamlit backend has elevated access and can still operate on these tables.
alter table public.cadets enable row level security;
alter table public.diagnostics enable row level security;
alter table public.diagnostic_answers enable row level security;
alter table public.training_sessions enable row level security;
alter table public.task_attempts enable row level security;
alter table public.ai_dialogues enable row level security;
alter table public.ai_tasks enable row level security;
